apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: front-end-app
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: front-nginx-1
      labels:
       env: production
    spec:
      containers: 
        - name: nginx
          image: nginx